spring:
  application:
    name: mic-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/config-repo
          searchPaths: '{application}'  #搜索各个以服务名命名的文件夹下的所有yml
server:
  port: 8889
eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/ #注册中心地址

logging:
  config: classpath:log4j2.xml