spring:
  application:
    name: mic-registry-server
server:
  port: 8888 # 注册中心占用8888端口
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #其实就是 http://localhost:8888/eureka/
logging:
  config: classpath:log4j2.xml